name: Auto Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto commit changes [skip ci]")
          git push 